### ISSUE TITLE
Nombre de la revista

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/revista#2]
Debemos definir el nombre de la revista.

Mi sugerencia es:

Revista Python Científico América Latina

Lo bueno de este nombre es que suena tanto en español como en portugués.

Hacemos un listado de opciones y después hacemos votación.

**Comment by Caaddss** [comment]
Penso que esse seria o melhor nome

**Comment by xmnlab** [comment]
Talvez apenas adicionar a palavra Informativa, para deixar claro o proposito da revista

**Comment by Caaddss** [comment]
excelente

**Comment by xmnlab** [comment]
Revista Informativa Python Científico América Latina
