### ISSUE TITLE
Template de la revista

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/revista#5]
Podríamos tener un template de la revista en latex.

**Comment by Caaddss** [comment]
Precisamos montar o template em LateX para as publicações em PDF, e o template Jenkyll para o blog post

**Comment by xmnlab** [comment]
opciones/opções:

1. http://flex.alxd.me/blog/ - https://github.com/alexandrevicenzi/Flex
2. https://raw.githubusercontent.com/PierrePaul/html5-dopetrope/master/screenshot.png - https://github.com/PierrePaul/html5-dopetrope

**Comment by xmnlab** [comment]
voto: 3 e 7

**Comment by nubol23** [comment]
2 y 5

**Comment by mavino4** [comment]
2

**Comment by relopezbriega** [comment]
2

**Comment by asnramos** [comment]
2

**Comment by Caaddss** [comment]
Posso dar close nessa issue?

**Comment by xmnlab** [comment]
Sim :)
