### ISSUE TITLE
Preparar chamada de trabalho artigos comunidade

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/revista#8]

**Comment by Caaddss** [comment]
o envio será via pull request certo?

eu penso que poderia ter um forms, pra pessoa preencher com a data que abriu o PR, um email pra contato, e o tema do trabalho, pq fica mais fácil pra gente colocar a tag e equilibrar as tags

**Comment by xmnlab** [comment]
poderia ser :)

talvez antes seria bom revisar como a galera do JOSS está fazendo isso:

https://joss.readthedocs.io/en/latest/submitting.html

vou tentar dar uma lida nisso na hora do almoço

**Comment by Caaddss** [comment]
Eles usam OrcID
Eles se cadastraram lá, e redireciona pro site deles

**Comment by Caaddss** [comment]
Pelo q vi do repo do site, acaba sendo PR, já flamos lá para gerar um markdown com as informações, acho que já temos um ótimo caminho...temos só que preparar mesmo os menus

**Comment by xmnlab** [comment]
OK .. vou trabalhar nos menus hoje de noite :)

**Comment by Caaddss** [comment]
blz, vou fechar esse então
